use crate::analysis::cfa::SectionAddress;
use crate::obj::{
    ObjInfo, ObjSplit, ObjSymbol, ObjSymbolFlagSet, ObjSymbolFlags, ObjSymbolKind, ObjUnit,
};
use anyhow::Result;
use base64::{Engine, engine::general_purpose::STANDARD};
use memchr::memmem;
use std::collections::BTreeMap;

// Try and find any common LIBCMT TU splits/symbols here
pub fn parse_libcmt(obj: &mut ObjInfo) -> Result<()> {
    // process_mem_funcs(obj)?;
    Ok(())
}

// LIBCMT funcs should be in .text
fn find_func_addr(obj: &ObjInfo, func_bytes: &str) -> Result<Option<SectionAddress>> {
    let func_bytes_decoded = STANDARD.decode(func_bytes)?;
    let (text_idx, text_section) = obj.sections.by_name(".text")?.expect("no text?");
    if let Some(pos) = memmem::find(&text_section.data, &func_bytes_decoded) {
        Ok(Some(SectionAddress::new(
            text_idx,
            text_section.address + pos as u32,
        )))
    } else {
        Ok(None)
    }
}

fn add_tu(
    obj: &mut ObjInfo,
    tu_name: &str,
    start: SectionAddress,
    end: SectionAddress,
) -> Result<()> {
    // only do this if we don't have splits (so for future runs this can be skipped)
    if !obj.sections[start.section]
        .splits
        .has_split_at(start.address)
    {
        obj.link_order.push(ObjUnit {
            name: String::from(tu_name),
            autogenerated: false,
            order: None,
        });
        obj.add_split(
            start.section,
            start.address,
            ObjSplit {
                unit: String::from(tu_name),
                end: end.address,
                align: None,
                ..Default::default()
            },
        )?;
    }
    Ok(())
}

fn process_mem_funcs(obj: &mut ObjInfo) -> Result<()> {
    const MEMSET: &str = "OAUAAXwJA6ZgZgAASAAAEDil//+YhgAAOMYAAXDAAANAAv/wUIRELlSg4T9QhIAeQeIAIHwJA6aQhgAAkIYABJCGAAiQhgAMOMYAEEMg/+xUoPe/QcIAKHwJA6aQhgAAOMYABENAABiQhgAAOMYABENAAAyQhgAAOMYABHCgAAN8CQOmTeIAIJiGAABPQAAgmIYAAU9AACCYhgACToAAIA==";
    if let Some(memset_addr) = find_func_addr(obj, MEMSET)? {
        obj.add_symbol(
            ObjSymbol {
                name: String::from("memset"),
                address: memset_addr.address,
                section: Some(memset_addr.section),
                size: 0xA0,
                size_known: true,
                flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
                kind: ObjSymbolKind::Function,
                ..Default::default()
            },
            false,
        )?;
        add_tu(
            obj,
            "xdk/LIBCMT/memsetp.cpp",
            memset_addr,
            memset_addr + 0xA0,
        )?;
    }

    const MEMCMP: &str = "KAUACEGAAFQ4AAAHVKfo/nygADh86QOm6MQAAOijAABIAAAM6MQACeijAAl8JTAAQQL/9EGCABg4YP//fCUwQE2AACA4YAABToAAIHwFA3g4YwAIOIQACCwFAAB8qQOmQYIAKIjEAACIowAASAAADIzEAAGMowABfAUwAEEC//R8ZihQToAAIDhgAABOgAAg";
    if let Some(memcmp_addr) = find_func_addr(obj, MEMCMP)? {
        obj.add_symbol(
            ObjSymbol {
                name: String::from("memcmp"),
                address: memcmp_addr.address,
                section: Some(memcmp_addr.section),
                size: 0x90,
                size_known: true,
                flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
                kind: ObjSymbolKind::Function,
                ..Default::default()
            },
            false,
        )?;
        add_tu(
            obj,
            "xdk/LIBCMT/memcmpp.cpp",
            memcmp_addr,
            memcmp_addr + 0x90,
        )?;
    }

    const MEMCHR: &str =
        "L4UAACyFAAFBngAsiMMAAH8GIAA4pf//QZoAIEGGABh8qQOmjMMAAXwGIABAAv/4QYIACDhgAABOgAAg";
    if let Some(memchr_addr) = find_func_addr(obj, MEMCHR)? {
        obj.add_symbol(
            ObjSymbol {
                name: String::from("memchr"),
                address: memchr_addr.address,
                section: Some(memchr_addr.section),
                size: 0x3C,
                size_known: true,
                flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
                kind: ObjSymbolKind::Function,
                ..Default::default()
            },
            false,
        )?;
        add_tu(
            obj,
            "xdk/LIBCMT/memchrp.cpp",
            memchr_addr,
            memchr_addr + 0x3C,
        )?;
    }

    // memmove and memcpy should be here thanks to the calls from entrypoint
    const MEMMOVE_MODIFIED: &str = "OAUAAXxjKhR8hCoUfAkDpkgAABg4pf//iAT//ziE//+YA///OGP//3BgAANAAv/oVKDwv0HCACR8CQOmcIAAA0DCADyA5P/8OIT//JDj//w4Y//8QyD/8HCgAAN8CQOmTeIAIIgE//84hP//mAP//zhj//9DIP/wToAAIIjk//84Y//8iQT//lEHRC6JJP/9USeCHolE//xRR8AOOIT//JDjAABCAP/YS///sA==";
    let memmove_addr = find_func_addr(obj, MEMMOVE_MODIFIED)?.expect("no memmove?") - 16;
    obj.add_symbol(
        ObjSymbol {
            name: String::from("memmove"),
            address: memmove_addr.address,
            section: Some(memmove_addr.section),
            size: 0xBC,
            size_known: true,
            flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
            kind: ObjSymbolKind::Function,
            ..Default::default()
        },
        false,
    )?;
    add_tu(
        obj,
        "xdk/LIBCMT/memmovep.cpp",
        memmove_addr,
        memmove_addr + 0xBC,
    )?;

    const MEMCPY_START: &str = "+GH/+FRmB358ACIsKAYAACDGAAg=";
    let memcpy_addr = find_func_addr(obj, MEMCPY_START)?.expect("no memcpy?");
    obj.add_symbol(
        ObjSymbol {
            name: String::from("memcpy"),
            address: memcpy_addr.address,
            section: Some(memcpy_addr.section),
            // the size can actually vary across xexes, so we can't definitively know it
            flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
            kind: ObjSymbolKind::Function,
            ..Default::default()
        },
        false,
    )?;
    const BLKMOV: &str = "OAUAAWBmAAB8CQOmSAAAGDil//+IBAAAOIQAAZgGAAA4xgABcMAAA0AC/+hUoPC/QcIAJHwJA6ZwgAADQMIAPIDkAAA4hAAEkOYAADjGAARDIP/wcKAAA3wJA6ZN4gAgiAQAADiEAAGYBgAAOMYAAUMg//BOgAAgiOQAA4kEAAJRB0QuiSQAAVEngh6JRAAAUUfADjiEAASQ5gAAOMYABEIA/9hL//+w";
    if let Some(blkmov_addr) = find_func_addr(obj, BLKMOV)? {
        obj.add_symbol(
            ObjSymbol {
                name: String::from("_blkmov"),
                address: blkmov_addr.address,
                section: Some(blkmov_addr.section),
                size: 0xA8,
                size_known: true,
                flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
                kind: ObjSymbolKind::Function,
                ..Default::default()
            },
            false,
        )?;
        if blkmov_addr > memcpy_addr {
            // memcpy and blkmov are the only two funcs in memcpyp.obj.
            // so, if blkmov is after memcpy, we know the start and end of the split
            add_tu(
                obj,
                "xdk/LIBCMT/memcpyp.cpp",
                memcpy_addr,
                blkmov_addr + 0xA8,
            )?;
        }
    }
    Ok(())
}
