use crate::analysis::cfa::SectionAddress;
use crate::obj::{
    ObjInfo, ObjSplit, ObjSymbol, ObjSymbolFlagSet, ObjSymbolFlags, ObjSymbolKind, ObjUnit,
};
use anyhow::Result;
use base64::{Engine, engine::general_purpose::STANDARD};
use memchr::memmem;
use std::collections::BTreeMap;

// Try and find any common LIBCMT TU splits/symbols here
pub fn parse_libcmt(obj: &mut ObjInfo) -> Result<()> {
    // crtgpr/fpr/vmx
    process_reg_intrinsics(obj)?;
    process_chkstk(obj)?;
    process_fpctrl(obj)?;
    process_u64tod(obj)?;
    Ok(())
}

// LIBCMT funcs should be in .text
fn find_func_addr(obj: &ObjInfo, func_bytes: &str) -> Result<SectionAddress> {
    let func_bytes_decoded = STANDARD.decode(func_bytes)?;
    let (text_idx, text_section) = obj.sections.by_name(".text")?.expect("no text?");
    if let Some(pos) = memmem::find(&text_section.data, &func_bytes_decoded) {
        Ok(SectionAddress::new(
            text_idx,
            text_section.address + pos as u32,
        ))
    } else {
        panic!("Function not found in .text!");
    }
}

fn add_tu(
    obj: &mut ObjInfo,
    tu_name: &str,
    start: SectionAddress,
    end: SectionAddress,
) -> Result<()> {
    // only do this if we don't have splits (so for future runs this can be skipped)
    if !obj.sections[start.section]
        .splits
        .has_split_at(start.address)
    {
        obj.link_order.push(ObjUnit {
            name: String::from(tu_name),
            autogenerated: false,
            order: None,
        });
        obj.add_split(
            start.section,
            start.address,
            ObjSplit {
                unit: String::from(tu_name),
                end: end.address,
                align: None,
                ..Default::default()
            },
        )?;
    }
    Ok(())
}

fn process_reg_intrinsics(obj: &mut ObjInfo) -> Result<()> {
    struct RegFuncInfo {
        name: &'static str,
        offset: u32,
        size: u32,
    }
    struct RegSledInfo {
        name_start: &'static str,
        offset: u32,
        start: u32,
        end: u32,
        step: u32,
    }

    struct RegSplitInfo {
        split_name: &'static str,
        split_size: u32,
        signature: &'static str,
        funcs: &'static [RegFuncInfo],
        sleds: &'static [RegSledInfo],
    }

    #[rustfmt::skip]
    const SLEDS_XBOX2: [RegSplitInfo; 3] = [
        RegSplitInfo {
            split_name: "xdk/LIBCMT/crtgpr.cpp", split_size: 0xB0, signature: "+cH/aPnh/3D6Af94+iH/gA==",
            funcs: &[ RegFuncInfo { name: "__savegprlr", offset: 0, size: 0x50, }, RegFuncInfo { name: "__restgprlr", offset: 0x50, size: 0x54, }, ],
            sleds: &[
                RegSledInfo { name_start: "__savegprlr_", offset: 0, start: 14, end: 32, step: 4, },
                RegSledInfo { name_start: "__restgprlr_", offset: 0x50, start: 14, end: 32, step: 4, },
            ],
        },
        RegSplitInfo {
            split_name: "xdk/LIBCMT/crtfpr.cpp", split_size: 0x98, signature: "2cz/cNns/3jaDP+A2iz/iA==",
            funcs: &[ RegFuncInfo { name: "__savefpr", offset: 0, size: 0x4C, }, RegFuncInfo { name: "__restfpr", offset: 0x4C, size: 0x4C, }, ],
            sleds: &[
                RegSledInfo { name_start: "__savefpr_", offset: 0, start: 14, end: 32, step: 4, },
                RegSledInfo { name_start: "__restfpr_", offset: 0x4C, start: 14, end: 32, step: 4, },
            ],
        },
        RegSplitInfo {
            split_name: "xdk/LIBCMT/crtvmx.cpp", split_size: 0x530, signature: "OWD+4H3LYc45YP7wfethzjlg/wB+C2HOOWD/EH4rYc4=",
            funcs: &[ RegFuncInfo { name: "__savevmx", offset: 0, size: 0x298, }, RegFuncInfo { name: "__restvmx", offset: 0x298, size: 0x298, }, ],
            sleds: &[
                RegSledInfo { name_start: "__savevmx_", offset: 0, start: 14, end: 32, step: 8, },
                RegSledInfo { name_start: "__savevmx_", offset: 0x94, start: 64, end: 128, step: 8, },
                RegSledInfo { name_start: "__restvmx_", offset: 0x298, start: 14, end: 32, step: 8, },
                RegSledInfo { name_start: "__restvmx_", offset: 0x32C, start: 64, end: 128, step: 8, },
            ],
        },
    ];

    for split in SLEDS_XBOX2 {
        let start_addr = find_func_addr(obj, split.signature)?;
        for func in split.funcs {
            obj.add_symbol(
                ObjSymbol {
                    name: func.name.to_string(),
                    address: start_addr.address + func.offset,
                    section: Some(start_addr.section),
                    size: func.size,
                    size_known: true,
                    flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
                    kind: ObjSymbolKind::Function,
                    ..Default::default()
                },
                false,
            )?;
        }
        for sled in split.sleds {
            for i in sled.start..sled.end {
                let addr = start_addr + sled.offset + (i - sled.start) * sled.step;
                obj.add_symbol(
                    ObjSymbol {
                        name: format!("{}{}", sled.name_start, i),
                        address: addr.address,
                        section: Some(addr.section),
                        size_known: true,
                        flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
                        ..Default::default()
                    },
                    false,
                )?;
            }
        }
        add_tu(
            obj,
            split.split_name,
            start_addr,
            start_addr + split.split_size,
        )?;
    }

    Ok(())
}

fn process_chkstk(obj: &mut ObjInfo) -> Result<()> {
    const RTL_CHECK_STACK: &str = "fYMA0H1sANA4Cw//fABmcUyBACB8Kwt4fAkDpoQL8ABCAP/8ToAAIA==";
    let rtl_check_stack_addr = find_func_addr(obj, RTL_CHECK_STACK)?;
    obj.symbols.add(
        ObjSymbol {
            name: String::from("_RtlCheckStack"),
            address: rtl_check_stack_addr.address,
            section: Some(rtl_check_stack_addr.section),
            size: 0x28,
            size_known: true,
            flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
            kind: ObjSymbolKind::Function,
            ..Default::default()
        },
        false,
    )?;
    obj.symbols.add(
        ObjSymbol {
            name: String::from("_RtlCheckStack12"),
            address: rtl_check_stack_addr.address + 4,
            section: Some(rtl_check_stack_addr.section),
            size_known: true,
            flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
            ..Default::default()
        },
        false,
    )?;
    add_tu(
        obj,
        "xdk/LIBCMT/chkstk.cpp",
        rtl_check_stack_addr,
        rtl_check_stack_addr + 0x28,
    )?;
    Ok(())
}

fn process_fpctrl(obj: &mut ObjInfo) -> Result<()> {
    struct FPCtrlFuncInfo {
        name: &'static str,
        offset: u32,
        size: u32,
    }
    #[rustfmt::skip]
    const FPCTRL_FUNCS: &[(&str, &[FPCtrlFuncInfo])] = &[
        ("/AAEjtgB//hoZQD4gGH//HylIDh8ZiB4fKYzeJDB//zIAf/4aGMA+P3+BY5OgAAg", &[FPCtrlFuncInfo { name: "_ctrlfp", offset: 0, size: 0x30, }],),
        ("/AAEjtgB//iAYf/8ToAAIPwABI44YAAE2AH/+ICh//x8ZSg4kKH//Mgh//j9/g2OToAAIA==",
            &[FPCtrlFuncInfo { name: "_statfp", offset: 0, size: 0x10, }, FPCtrlFuncInfo { name: "_FPreset", offset: 0x10, size: 0x24, } ],),
        ("/AAEjtgB//iAof/8fGUreJCh//zIIf/4/f4Njk6AACCQYf/8yCH/+P3+DY5OgAAg/AAEjtgB//iAYf/8ToAAIA==",
            &[FPCtrlFuncInfo { name: "_set_statfp", offset: 0, size: 0x20, }, FPCtrlFuncInfo { name: "_set_fsr", offset: 0x20, size: 0x10, }, FPCtrlFuncInfo { name: "_get_fsr", offset: 0x30, size: 0x10, } ],),
    ];
    let mut found_funcs: BTreeMap<SectionAddress, u32> = BTreeMap::new();
    for &(func_bytes, func_infos) in FPCTRL_FUNCS {
        let addr = find_func_addr(obj, func_bytes)?;
        for info in func_infos {
            obj.add_symbol(
                ObjSymbol {
                    name: String::from(info.name),
                    address: addr.address + info.offset,
                    section: Some(addr.section),
                    size: info.size,
                    size_known: true,
                    flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
                    kind: ObjSymbolKind::Function,
                    ..Default::default()
                },
                false,
            )?;
            found_funcs.insert(addr + info.offset, info.size);
        }
    }
    add_tu(
        obj,
        "xdk/LIBCMT/fpctrl.cpp",
        *found_funcs.first_key_value().unwrap().0,
        found_funcs.last_key_value().map(|(k, v)| *k + *v).unwrap(),
    )?;
    Ok(())
}

fn process_u64tod(obj: &mut ObjInfo) -> Result<()> {
    const U64TOD: &str = "fGUAdHxjKDYsIwAAQYIAECClBD54Y6sCeKOgTvhh//jIIf/4ToAAIA==";
    let u64tod_addr = find_func_addr(obj, U64TOD)?;
    obj.symbols.add(
        ObjSymbol {
            name: String::from("__u64tod"),
            address: u64tod_addr.address,
            section: Some(u64tod_addr.section),
            size: 0x28,
            size_known: true,
            flags: ObjSymbolFlagSet(ObjSymbolFlags::Global.into()),
            kind: ObjSymbolKind::Function,
            ..Default::default()
        },
        false,
    )?;
    add_tu(
        obj,
        "xdk/LIBCMT/u64tod.cpp",
        u64tod_addr,
        u64tod_addr + 0x28,
    )?;
    Ok(())
}
